### ISSUE TITLE
BUG: split read ins!

### ISSUE THREAD

**Issue by jdmontenegro** [fritzsedlazeck/Sniffles#200]
Hi Fritz,

I am trying to run a job on a large genome (2.8Gb). This is the consensus of a ighly heterozygous genome, so there should be a fair amount of heterozygous SV. I am getting an error in the first contig (42 thousand contigs in total). The command line was as follows:

```
sniffles -z 3 -d 10000 -t 26 -n -1 --report_BND --genotype --cluster --min_het_af 0.2 -m inia601.bam -v inia601.vcf
Estimating parameter...
        Max dist between aln events: 4
        Max diff in window: 50
        Min score ratio: 2
        Avg DEL ratio: 0.0315592
        Avg INS ratio: 0.154157
Start parsing... ctg1
BUG: split read ins! 6123 2852 m54329U_200324_174744/150668912/36192_62717
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
/var/spool/slurm/job4679576/slurm_script: line 38: 32633 Aborted                 (core dumped) sniffles -z 3 -d 10000 -t 26 -n -1 --report_BND --genotype --cluster --min_het_af 0.2 -m $bam -v inia601.vcf

```
I was trying to look for similar errors in this page, but they all seem to be at least half a year old and none related to any of the flags used for this run.  could you perhaps point me in the right direction, what could be going wrong here?

Cheers,

Juan D. Montenegro

**Comment by fritzsedlazeck** [comment]
Dear Juan,
can you maybe provide the bam file for this one contig? The read with this read name ( m54329U_200324_174744/150668912/36192_62717) is causing this error. 

I have never seen this error before and the code is in there since many years :) 

Thank you
Fritz

**Comment by jdmontenegro** [comment]
Dear Fritz,
I have extracted the alignments for ctg1 alone ad managed to replicate the bug. It is 19Mb bam file, how could I share it with you? Google drive would be ok? Send me your email and I will share it with you.

Cheers,

Juan D. Montenegro

**Comment by fritzsedlazeck** [comment]
fritz.sedlazeck@gmail.com 
Not promising to take a look today or tomorrow... 
Thanks
Fritz

**Comment by jdmontenegro** [comment]
Thank you Fritz
I understand probably have a ton of things in your hands. I have already
shared it with you. Let me know if there is anything else I can do to help.

Cheers,

Juan D. Montenegro

**Comment by fritzsedlazeck** [comment]
Yeah maybe can you give me the sequence of contig1 ? So I can take a look at IGV if I need to debug something.
Thanks
Fritz

**Comment by jdmontenegro** [comment]
I just put it in the drive.
thank you again.
Kind regards,

Juan D.

**Comment by yusmiatiliau** [comment]
Hi,

I got a similar error trying to run sniffles on one human genome nanopore data (11 Gb), mapped using minimap2. 

sniffles -m /bam file/ -v /vcf file/ -s 2 -t 4 
resulted in this error:

Estimating parameter...
        Max dist between aln events: 9
        Max diff in window: 50
        Min score ratio: 2
        Avg DEL ratio: 0.0388139
        Avg INS ratio: 0.0288268
Start parsing... chr1
BUG: split read ins! 9159 5855 a472e554-5071-4459-861a-93c9aa8f9ce8
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 8249) > this->size() (which is 5855)
Aborted (core dumped)

will be thankful if you can advise what should I do to overcome the error?

Thanks

**Comment by GokuAK** [comment]
> Hi,
> 
> I got a similar error trying to run sniffles on one human genome nanopore data (11 Gb), mapped using minimap2.
> 
> sniffles -m /bam file/ -v /vcf file/ -s 2 -t 4
> resulted in this error:
> 
> Estimating parameter...
> Max dist between aln events: 9
> Max diff in window: 50
> Min score ratio: 2
> Avg DEL ratio: 0.0388139
> Avg INS ratio: 0.0288268
> Start parsing... chr1
> BUG: split read ins! 9159 5855 a472e554-5071-4459-861a-93c9aa8f9ce8
> terminate called after throwing an instance of 'std::out_of_range'
> what(): basic_string::substr: __pos (which is 8249) > this->size() (which is 5855)
> Aborted (core dumped)
> 
> will be thankful if you can advise what should I do to overcome the error?
> 
> Thanks



> 你好
> 
> 我尝试对使用minimap2映射的一个人类基因组纳米孔数据（11 Gb）进行嗅探时遇到类似的错误。
> 
> 嗅-m / bam文件/ -v / vcf文件/ -s 2 -t 4
> 导致此错误：
> 
> 估计参数...
> aln事件之间的最大距离：9
> 窗口中的最大差异：50
> 最小得分比：2
> 平均DEL比：0.0388139
> 平均INS比：0.0288268
> 开始解析... chr1
> 错误：分割读入文件！9159 5855 a472e554-5071-4459-861a-93c9aa8f9ce8引发
> 'std ::
> out_of_range'what（）实例后终止调用what（）：basic_string :: substr：__pos（8249）> this-> size（）（5855） ）
> 中止（核心转储）
> 
> 如果您能提出解决该错误的建议，我们将不胜感激。
> 
> 谢谢

**Comment by GokuAK** [comment]
Hi,

I also got the same error，is there sth wrong with the special contig？
waiting for the solution.
thx so much !

**Comment by fritzsedlazeck** [comment]
I think I just fixed it. The problem was that the alignment or this read does not have a primary alignment and also got through my primary alignment checks. 

I just pushed the code and please test it out and report back if that looks good.
Thanks
fritz

**Comment by jdmontenegro** [comment]
Thank you Fritz,

It sounds weird that a read did not have a primary alignment. Even if it
has the same score as the secondary alignment it should still have a
primary one. Perhaps a bug in mínimap?

Cheers,

Juan Daniel

**Comment by fritzsedlazeck** [comment]
exaclty, but a simple grep on the read name in the bam file:
`54329U_200324_174744/150668912/36192_62717     2048    ctg1    1       60      2274H10M2I7M1I8M2I5M2I18M1I38M1D17M1I17M1I2M1I46M1I24M1I26M1I8M2I52M1I14M1D21M1I29M1I21M2I8M1I12M2D37M1I7M1I14M1D4M4I3M1D5M1I9M2I6M1I3M1D9M2I7M1I19M1D4M1I4M1D4M2I5M3I6M3I4M1I5M1I5M1I17M1I10M1I8M1I18M1I4M1I5M2I50M2I8M1I27M2I2M1I13M2I11M1I11M1I3M1I7M1I17M1I10
m54329U_200324_174744/150668912/36192_62717     2048    ctg1    2777    60      6123H13M1I11M1D3M1I9M1I5M1I2M1I35M1D8M2I14M3I65M1I15M4I20M1I6M2I20M1I8M2I2M1I17M3I12M1D7M1I6M1I1M1D20M1I5M1I7M1I30M1D17M1I3M1I7M1I35M3I1M4I2M1I4M3I1M3I8M1I4M1I8M1I23M1D4M1D7M1I2M1I11M1I38M1D2M1D13M1D17M1I12M1I14M1D10M1I14M2I7M1I10M1D25M1I14M1I12M1I39M1I7M1D`

so both are 2048 as a tag. If we look that up it says supplement alignment. 

cheers
Fritz

**Comment by GokuAK** [comment]
> exaclty, but a simple grep on the read name in the bam file:
> `m54329U_200324_174744/150668912/36192_62717 2048 ctg1 1 60 2274H10M2I7M1I8M2I5M2I18M1I38M1D17M1I17M1I2M1I46M1I24M1I26M1I8M2I52M1I14M1D21M1I29M1I21M2I8M1I12M2D37M1I7M1I14M1D4M4I3M1D5M1I9M2I6M1I3M1D9M2I7M1I19M1D4M1I4M1D4M2I5M3I6M3I4M1I5M1I5M1I17M1I10M1I8M1I18M1I4M1I5M2I50M2I8M1I27M2I2M1I13M2I11M1I11M1I3M1I7M1I17M1I10
> 
> m54329U_200324_174744/150668912/36192_62717 2048 ctg1 2777 60 6123H13M1I11M1D3M1I9M1I5M1I2M1I35M1D8M2I14M3I65M1I15M4I20M1I6M2I20M1I8M2I2M1I17M3I12M1D7M1I6M1I1M1D20M1I5M1I7M1I30M1D17M1I3M1I7M1I35M3I1M4I2M1I4M3I1M3I8M1I4M1I8M1I23M1D4M1D7M1I2M1I11M1I38M1D2M1D13M1D17M1I12M1I14M1D10M1I14M2I7M1I10M1D25M1I14M1I12M1I39M1I7M1D`
> 
> so both are 2048 as a tag. If we look that up it says supplement alignment.
> 
> cheers
> Fritz

Exceuse me，I am just a beginner and I don't understand the meaning  of “this read does not have a primary alignment and also got through my primary alignment checks.”
So it is due to a bug of minimap2 ? how about the ngmlr?
thx a lot for your replay.

**Comment by fritzsedlazeck** [comment]
So typically it is required to have at least 1 primary alignments, but for that particular read I dont see one in the bam file. Might be because of the extracted reads that Juan sent me.  Also it seems that my bam parser libraries things they are primary alignments, but they are not. So I added an extra check. 


So I dont know if that is a bug from the aligner, but it should work now. 

Thanks
Fritz

**Comment by GokuAK** [comment]
ok，I’ll have a try.
thank you so much！

**Comment by fritzsedlazeck** [comment]
Np. Sorry for the delay. 
Cheers
Fritz

**Comment by GokuAK** [comment]
HI，Fritz

  I want to let you know that when I  update the Sniffles, it runs successfully. But there are only two Scaffold output to the VCF file.
  Here is the nohup message :
Estimating parameter...
        Max dist between aln events: 105
        Max diff in window: 103
        Min score ratio: 2
        Avg DEL ratio: 0.0178153
        Avg INS ratio: 0.0227927
Start parsing... A01
        Switch Chr A02
                Reassessing breakpoints
                Continue parsing
        Switch Chr A03
                Reassessing breakpoints
                Continue parsing
                # Processed reads: 10000
        Switch Chr A04
                Reassessing breakpoints
                Continue parsing
        Switch Chr A05
                Reassessing breakpoints
                Continue parsing
        Switch Chr A06
                Reassessing breakpoints
                Continue parsing
                # Processed reads: 20000
.
.
.
                Switch Chr C06
                Switch Chr C08
                Switch Chr C09
        Finalizing  ..

And when I use minimap2 to map another sample，the sam file couldn't be recognized by samtools，so I guess there are sth wrong with my minimap or sam file.
Now I decide to change to use ngmlr, I'll reply to you later if it works.

**Comment by fritzsedlazeck** [comment]
For minimap2 you need to use -a for sam output (and add --MD).  NGMLR runs much slower but is often a bit more accurate. 

About the output: Check your coverage etc. you might need to adjust (e.g. -s. )
Cheers
Fritz

**Comment by GokuAK** [comment]
my minimap command ： minimap2 -L --MD -ax map-pb Ref.fa sample.fa > sample.sam
my Sniffles command: sniffles --min_support 10 --max_num_splits 7 --max_distance 1000 --min_length 30 -m Sample_sort.bam -v Sample.vcf

**Comment by fritzsedlazeck** [comment]
Can someone confirm that this is solved? if so I will close that issue. 
Thanks
Fritz

**Comment by chen318liang** [comment]
I meet the same error when doing the SV calling for a population unsing minimap2 as alignment tool. 
The error is below,
Start parsing: Chr NODE_5_length_552402_cov_42.966954
BUG: split read ins! 3007 329 08742842-dcb0-4217-9424-1c69eeff64b4
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 338) > this->size() (which is 329)
	Force calling mode enabled. Setting parameter accordingly

My sniffles version is 1.0.12 installed by conda. 
my command is below,

minimap2 -ax map-ont -t 48 --MD  nano.${sample}.dehost.fq.gz > nano.${sample}.dehost.sam
samtools sort -T ref_sniffles nano.${sample}.dehost.sam -o nano.${sample}.dehost.bam -@ 48
sniffles -t 48 --genotype -m nano.${sample}.dehost.bam -v nano.${sample}.dehost.vcf

SV calling for a population:
ls nano.*.dehost.vcf >vcf_files_raw_calls.txt
SURVIVOR merge vcf_files_raw_calls.txt 1000 1 1 -1 -1 -1 merged_SURVIVOR_1kbpdist_typesave.vcf
sniffles -t 48 --genotype -m nano.${sample}.dehost.bam -v nano.${sample}.dehost.gt.vcf --Ivcf merged_SURVIVOR_1kbpdist_typesave.vcf

The error occurred in the last command!

**Comment by fritzsedlazeck** [comment]
We just pushed a completely new version of Sniffles (v2.0.0.2) and hope this will be resolved.
