### ISSUE TITLE
--report_seq core dump

### ISSUE THREAD

**Issue by bjarnivh** [fritzsedlazeck/Sniffles#28]
When I run sniffles-1.0.6 with the --report_seq option I get:

terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
Aborted (core dumped)

This does not happen when I don't use the --report_seq option.  Without that option the program gives interesting results, thanks.

The problem seems to occur around the time the first vcf record it being output, 1-5 minutes into the run of the program.   The error occurs for 4 out of 5 bam files I was working with, while the fifth one worked OK.

**Comment by fritzsedlazeck** [comment]
Hi,
Thanks for reporting this. Yes this option is yet not well tested. I will try to resolve this bug and test it more extensively.

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi,
I just pushed a fixed version. Keep in mind that this option is still a alpha version, but please go ahead and test it out. Plus please keep me posted. 
Thanks
Fritz

**Comment by bjarnivh** [comment]
Thank you for your quick response.  I still get a similar problem:

BUG: split read ins!
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr
/var/lib/slurm/slurmd/job121553723/slurm_script: line 2:   887 Aborted                 (core dumped) ./sniffles-1.0.7 -m sample.bam --report_seq -n -1 -t 8 -s 2 -v
 sample_sniffles_s2_report_seq.vcf

**Comment by fritzsedlazeck** [comment]
Thanks for letting me know. I have started some test runs , but didn't yet look at the results. I will correct it tomorrow and keep you posted.
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Hi, I ran the trio from GiaB and a Arabidopsis trio, but I wasn't able to reproduce the error. 
I can of course fix that error such that it doesn't stop the program, but that is not optimal.
Is there a chance you can narrow the problem down to a few reads and maybe share that region with me?

Please just ping me:  fritz.sedlazeck@gmail.com

Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Thanks for sending me a sample from your data. I think I corrected that bug.
I ran a couple of test sets to see if everything checks out and it did. Please update your copy and give it another try. 
I appreciate your help.
Thanks
Fritz

**Comment by bjarnivh** [comment]
Thanks, the new version seems to work correctly.
Bjarni

**Comment by fritzsedlazeck** [comment]
Perfect. Thanks for the feedback and let me know if you have further questions. 
Thanks
Fritz

**Comment by fritzsedlazeck** [comment]
Dear Bjarni,
please get the latest version of the code. There was a bug in the sequence that was reported for split read alignments. I just put up a new version.
Thanks
Fritz
